### PR TITLE
Add timetravel

### LINKED ISSUE #17: [Feature request] "Time travel" to see grid as it would've been in the past
It'd be nice to have a time travel feature to show what the grid looked liked at a certain date/time. For looking back at the progress one's made or etc.

Then again maybe spending too much time in the past could be detrimental, which might be why it wasn't already added 😅

### PR DESCRIPTION
**Pull request by iamllama**
Closes #17

> Also you can probably get a decent view of the past already just by adding some sort of date range to the additional search filters. Obviously the strength colors wont be accurate but the kanji should be.

Given the number of casual users, it'd be easier for them to have a date picker. And if we had to go to the trouble of adding one, it wouldn't take much more to make it full-featured

I don't have any strong opinions about the added UI (in config and the grid html), please rework them as you see fit 🙏

### CODE REVIEW

**Comment by Kuuuube** [comment]
If you're going to use the config to hold the values you're adding, they should be in the config file and the config util.

Also I feel like this is something regular users will never use or want. It will probably just be confusing to have in the UI so I think it would be best to make `config.timetravel_enabled` be what adds this to the UI. And whether timetravel should be calculated can be checked based on the calendar/date picker being changed from the default.

**Comment by iamllama** [comment]
> If you're going to use the config to hold the values you're adding, they should be in the config file and the config util. The config should also control the defaults rather than hardcoding defaults.

I don't understand, config is also set by the UI elements, which would include the datepicker. It wouldn't make sense to add a default for the datepicker because we'd just use the current time. Sure, the timestamp can be drilled through `makegrid` and then `kanjigrid`, but it just seems more convoluted

https://github.com/Kuuuube/kanjigrid/blob/61aa2b509e4e7060ac9c2cdd0a1cf1591d736b82/__init__.py#L205-L213

> Also I feel like this is something regular users will never use or want.

I disagree, this seems like an extension of the already-existing exporting feature

> It will probably just be confusing to have in the UI so I think it would be best to make config.timetravel_enabled be what adds this to the UI.

But if it's hidden by default then that might just be a self-fulfilling prophecy

**Comment by Kuuuube** [comment]
My problem is more that this adds an exception. Everything else is controllable in the config file except for this. Even though it isn't particularly useful to make it controllable by the config file, I feel like it should be. For a default, it could just be `null` and `None`. (python json parses `null` to `None`)

For the UI concerns, I've changed around the layout of the setup window a bit to help with this. This setting can be added to the `Advanced` tab so it's still discoverable but shouldn't seem confusing for new users.
image

**Review by Kuuuube — APPROVED** [review]
I've made a few changes, just a bit of cleanup in the code and some styling changes with the UI. This is what it looks like now on the advanced tab: 
image

If the user doesnt touch the time travel input box, it will set time travel to false. If they do touch it, it will enable time travel. No need for ticking the tiny hard to see groupbox checkbox.

The actual timetravel logic looks fine and in my testing it works great.

Unless you have any issues with the changes I've made, I'll go ahead and merge this.

**Comment by iamllama** [comment]
Got sidetracked for a spell, sorry for the delay 😅 The changes look great, thanks for working on it!

**Pull request merged**
